### ISSUE TITLE
Why stylelint loader caches files?

### ISSUE THREAD

**Issue by tqmukas** [adrianhall/stylelint-loader#10]
Hi,
Could you please explain what is the point to cache files in stylelint loader? 
In the current implementations linter checks each file only once. 

Let's take an example. One of project style files has lint error:
1. User runs webpack dev server.
2. User sees stylelint error.
3. User does some changes on the same file, but doesn't fix the problem.
4. Webpack re-rebundles files.
5. User doesn't see the error anymore.
6. However the lint error still exist.

Looks like a bug for me.

P. S. Temporary workaround to add `ignoreCache: true` to webpack config file.

**Comment by adrianhall** [comment]
Under certain configuration of webpack, you can end up scanning the same file twice, resulting in double the errors.  The second set of errors were completely un-necessary.  Not a bug - it's by design.

**Comment by tqmukas** [comment]
Can you please provide Webpack configuration example that works? Sounds really weird that default stylelint configuration doesn't work with webpack dev server.
