### ISSUE TITLE
ERROR in Cannot find module 'chalk'

### ISSUE THREAD

**Issue by RinatMullayanov** [adrianhall/stylelint-loader#11]
Hi,
Tell me please why I get error when I run webpack with style-loader?:
`ERROR in Cannot find module 'chalk'`

Node: v4.4.2
NPM: 2.15.3
OS: Windows 10

**Comment by adrianhall** [comment]
I've got some things that are dependencies in devDependencies.  Sorry about that - I'll get a new version out today.

**Comment by adrianhall** [comment]
Fixed in v5.0.1, just released.
