### ISSUE TITLE
Upgrade for newer stylelint?

### ISSUE THREAD

**Issue by g2graman** [adrianhall/stylelint-loader#12]
`npm install --save-dev stylelint` will currently install `stylelint@6.2.1` which causes stylelint-loader to give an EPEERINVALID

**Comment by melv-n** [comment]
**+1**

How can we solve this? @adrianhall

**Comment by g2graman** [comment]
This would work by upgrading the peer dependency accordingly in `package.json` and testing that the two are compatible.

**Comment by adrianhall** [comment]
Agreed with both of you.  I just haven't had a chance to sit down and do it.  When a new major version comes out, I update the peerDependency, then run the test suite.  If the test suite passes, it's a release.   Hoping to do that today.

**Comment by chapati23** [comment]
using the newest stylelint w/o any problems.
+1 for updating peerDependency

**Comment by adrianhall** [comment]
Published stylelint-loader v6.0.0

**Comment by melv-n** [comment]
Thanks @adrianhall !
