### ISSUE TITLE
Chalk is not defined in package.json

### ISSUE THREAD

**Issue by georgespyropoulos** [adrianhall/stylelint-loader#3]
I'm seeing the `ERROR in Cannot find module 'chalk'` when using this loader.

I believe that the issue is that chalk is not defined as a dependency of this module.  This wasn't an issue for me running under npm v3 as it has has flat module dependencies and chalk is a dependency of stylelint.  I picked up the issue when running webpack using npm v2.  Chalk is not available to stylelint-loader when using npm v2 and this causes the above error

**Comment by adrianhall** [comment]
Thanks for the fix!  Will be in the next release.
