### ISSUE TITLE
Change stylelint-loader default config file to .stylelintrc

### ISSUE THREAD

**Issue by pluma** [adrianhall/stylelint-loader#6]
Currently the loader will emit warnings about the configFile missing even if it hasn't been specified. As styleloader will happily figure out the correct configFile by itself (or fall back to the package.json config) this seems redundant.

A workaround is explicitly adding `stylelint: {configFile: false}` to the webpack config to avoid the loader's warnings.

**Comment by adrianhall** [comment]
I deliberately did this.  In general, the webpack.config.js should be explicit - I've found that adding the explicit configuration file is easy enough and adding an explicit flag that says "I really meant to not specify a configuration file" is also easy enough.  

Your workaround is how I intended the functionality to work.  I should probably document it though.

**Comment by pluma** [comment]
Okay, but the reason this blew up for me was that I followed the stylelint readme and called the file `.stylelintrc` -- whereas the loader's default is `.stylelint.config.js`. I use the stylelint CLI alongside the loader so I want to keep the configuration in one place both tools can find it.

That particular variant (with the leading dot) also isn't mentioned in [the cosmiconfig readme](https://www.npmjs.com/package/cosmiconfig) so I'm not sure whether the stylelint CLI would find the file the loader uses as default -- but maybe that's intentional too?

I think documenting this should suffice.

**Comment by adrianhall** [comment]
Good point - I should alter the default configuration to be .stylelintrc in the current directory.

Will update - and close once I'm done and released.

**Comment by adrianhall** [comment]
Fixed in 4.6.0
