### ISSUE TITLE
stylelint does not run when webpack-hot-reloader is used

### ISSUE THREAD

**Issue by adrianhall** [adrianhall/stylelint-loader#9]
Set up a hot reloader config with stylelint in the preLoaders.  Configure another preloader for eslint.

When the reloader rebuilds the package, note that eslint is run, but stylelint is not.

**Comment by adrianhall** [comment]
Fixed by switching to the plugin mechanism.

**Comment by ccastarivale** [comment]
@adrianhall I'm running into this exact problem. When you say 'switching to the plugin mechanism', do you mean stylelint-webpack-plugin? Is hot reloading supported by stylelint-loader?

**Comment by adrianhall** [comment]
Yes, I mean stylelint-webpack-plugin.  This is one of the issues that caused the switch.  This package is no longer maintained.

**Comment by ccastarivale** [comment]
Got it. Thanks
